from unum import Unum
unit = Unum.unit

m = M = unit("m", 0, "meter")
nm = NM = unit("nm", 10**-9 * m, "nanometer")
um = UM = unit("um", 10**-6 * m, "micrometer")
mm = MM = unit("mm", 10**-3 * m, "millimeter")
cm = CM = unit("cm", 10**-2 * m, "centimeter")
dm = DM = unit("dm", 10**-1 * m, "decimeter")
s = S = unit("s", 0, "second")
ks = KS = unit("ks", 10**3 * s, "kilosecond")
ps = PS = unit("ps", 10**-12 * s, "picosecond")
ns = NS = unit("ns", 10**-9 * s, "nanosecond")
us = US = unit("us", 10**-6 * s, "microsecond")
ms = MS = unit("ms", 10**-3 * s, "millisecond")
A = A = unit("A", 0, "ampere")
mA = MA = unit("mA", 10**-3 * A, "milliampere")
K = K = unit("K", 0, "kelvin")
mol = MOL = unit("mol", 0, "mole")
cd = CD = unit("cd", 0, "candela")
kg = KG = unit("kg", 0, "kilogram")
g = unit("g", 10**-3 * kg, "gram")
rad  = RAD         = unit( 'rad'   , M / M          , 'radian'   )
sr   = SR          = unit( 'sr'    , M**2 / M**2    , 'steradian')
Hz   = HZ      = unit( 'Hz'    , 1 / S          , 'hertz'      )
N    = N       = unit( 'N'     , M*KG / S**2    , 'newton'     )
Pa   = PA      = unit( 'Pa'    , N / M**2       , 'pascal'     )
J    = J       = unit( 'J'     , N*M            , 'joule'      )
W    = W       = unit( 'W'     , J / S          , 'watt'       )
C    = C       = unit( 'C'     , S * A          , 'coulomb'    )
V    = V       = unit( 'V'     , W / A          , 'volt'       )
F    = F       = unit( 'F'     , C / V          , 'farad'      )
ohm  = OHM     = unit( 'ohm'   , V / A          , 'ohm'        )
S    = SIEMENS = unit( 'S'     , A / V          , 'siemens'    )
Wb   = WB      = unit( 'Wb'    , V * S          , 'weber'      )
T    = T       = unit( 'T'     , WB / M**2      , 'tesla'      )
H    = HENRY   = unit( 'H'     , WB / A         , 'henry'      )
# warning : conversion assumes relative temperatures
celsius = CELSIUS = unit( 'deg C' , K         , 'degree Celsius' )
lm      = LM      = unit( 'lm'    , CD * SR   , 'lumen'          )
lx      = LX      = unit( 'lx'    , LM / M**2 , 'lux'            )
Bq      = BQ      = unit( 'Bq'    , 1 / S     , 'becquerel'      )
Gy      = GY      = unit( 'Gy'    , J / KG    , 'gray'           )
Sv      = SV      = unit( 'Sv'    , J / KG    , 'sievert'        )
kat     = KAT     = unit( 'kat'   , MOL / S   , 'katal'          )
## ===================== structural engineering units
G       = unit('G', 9.80665 * M/S**2,'gravity acceleration')
MPA     = unit('MPa', PA*(10**6),'megapascals')
KPA     = unit('KPa', PA*(10**3),'kilopascals')
KN      = unit('KN', N*(10**3),'kilonewton')
MN      = unit('MN', N*(10**6),'meganewton')
IN      = unit('in', M / 39.370079 , 'inch')
FT      = unit('ft', M / 3.2808399 , 'foot')
LBM     = unit('lbm', KG / 2.2046226, 'pound-mass')
LBF     = unit('lbs', N*4.4482216, 'pound-force')
KIPS    = unit('kips', LBF*1000. , 'kilopounds')
KIP     = unit('kip', LBF*1000., 'kilopound')
FT_KIPS = unit('ft-kips', FT*LBF*1000., 'foot-kips')
IN_KIPS = unit('in-kips', IN*LBF*1000., 'inch-kips')
MILES   = unit('miles', FT * 5280, 'miles')
SF      = unit('sf', FT**2, 'square feet')
PSF     = unit('psf', LBF/FT**2, 'pounds per square foot')
PSI     = unit('psi', LBF/IN**2, 'pounds per square inch')
KSI     = unit('ksi', KIPS/IN**2, 'kips per square inch')
KLI     = unit('kips/in', KIPS/IN, 'kips per inch')
PLI     = unit('lbf/in', LBF/IN, 'pounds per inch')
PLF     = unit('lbf/ft', LBF/FT, 'pounds per foot')
PCF     = unit('pcf',LBF/FT**3,'pounds per cubic ft')
FAHR    = unit('degF', K*9./5 , 'degree Fahrenheit')
DEGR    = unit('degrees',RAD*(2*3.14)/360,'degrees')
HR      = unit('hr',60*60*S,'hours')
MPH     = unit ('mph',MILES / HR, 'miles per hour')
